services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
  migrate:
    build:
      context: .
      target: migrate
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_HOST: db
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    expose:
      - ${DATABASE_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 10
    command: -p ${DATABASE_PORT}

