services:
  server:
    extends:
      file: common-services.yaml
      service: app
    build:
      target: dev
    env_file:
      - ./.env
    ports:
      - 3000:3000
      - 9229:9229
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/src/app/src
    depends_on:
      migrate:
        condition: service_completed_successfully
  migrate:
    extends:
        file: common-services.yaml
        service: migrate
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    extends:
      file: common-services.yaml
      service: db
    env_file:
    - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: